//! Where data came from, how fresh it is, and whether it's real.

use std::fmt;

use serde::{Deserialize, Serialize};

use crate::time::UnixNanos;

/// Stable provider identifier, e.g. `"mock"`, `"coinbase"`, `"edgar"`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct ProviderId(pub String);

impl ProviderId {
    #[must_use]
    pub fn new(s: &str) -> Self {
        Self(s.to_owned())
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ProviderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// How delayed the data is relative to the event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DataDelay {
    RealTime,
    Delayed { minutes: u32 },
    EndOfDay,
    /// Generated by the mock provider. Never real.
    Synthetic,
}

impl DataDelay {
    /// Short badge text shown in the UI.
    #[must_use]
    pub fn badge(self) -> String {
        match self {
            DataDelay::RealTime => "RT".into(),
            DataDelay::Delayed { minutes } => format!("DLY {minutes}"),
            DataDelay::EndOfDay => "EOD".into(),
            DataDelay::Synthetic => "MOCK".into(),
        }
    }
}

/// What the "real-time" number actually represents. Many retail feeds are a
/// single venue or a model, and the UI must say so.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FeedSource {
    /// Consolidated tape (CTA/UTP SIP) or equivalent full-market feed.
    Consolidated,
    /// One venue only, e.g. `"IEX"`, `"EDGX"`.
    SingleVenue(String),
    /// Direct feed of a single exchange that *is* the market (crypto venue,
    /// CME Globex).
    Exchange(String),
    /// Vendor aggregate across venues (CoinGecko, reference FX).
    Aggregated,
    /// Official statistical/regulatory source (SEC, FRED, Treasury).
    Official,
    /// Vendor-modelled or derived price, not exchange prints.
    Modelled,
    /// Generated by the mock provider.
    Synthetic,
}

impl FeedSource {
    #[must_use]
    pub fn label(&self) -> String {
        match self {
            FeedSource::Consolidated => "CONSOL".into(),
            FeedSource::SingleVenue(v) | FeedSource::Exchange(v) => v.to_ascii_uppercase(),
            FeedSource::Aggregated => "AGG".into(),
            FeedSource::Official => "OFFICIAL".into(),
            FeedSource::Modelled => "MODEL".into(),
            FeedSource::Synthetic => "MOCK".into(),
        }
    }
}

/// Attached to every response type.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Provenance {
    pub provider: ProviderId,
    pub synthetic: bool,
    pub delay: DataDelay,
    pub source: FeedSource,
    /// When the provider produced or we fetched this payload.
    pub as_of: UnixNanos,
    /// URL, accession number, or vendor ID for audit.
    pub source_ref: Option<String>,
    /// Attribution text that the provider's terms require on screen.
    pub attribution: Option<String>,
}

impl Provenance {
    #[must_use]
    pub fn synthetic(as_of: UnixNanos) -> Self {
        Self {
            provider: ProviderId::new("mock"),
            synthetic: true,
            delay: DataDelay::Synthetic,
            source: FeedSource::Synthetic,
            as_of,
            source_ref: None,
            attribution: None,
        }
    }

    #[must_use]
    pub fn with_ref(mut self, r: impl Into<String>) -> Self {
        self.source_ref = Some(r.into());
        self
    }
}
